# Generated by Django 4.0.4 on 2022-06-15 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0002_alter_appuser_options_alter_appuser_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('users', models.ManyToManyField(blank=True, to='userapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, verbose_name='Текст задания')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Задание создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Задание обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Задание активно')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.appuser', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
