# Generated by Django 4.0.4 on 2022-05-11 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
            ],
        ),
    ]
