# Generated by Django 4.0.4 on 2022-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_category',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Менеджер проекта'), ('D', 'Разработчик')], default='M', max_length=1),
        ),
    ]
